
version: "3"
services:
  web:
    image: "nginx:latest"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    expose:
      - 80
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    command: tunnel --no-autoupdate run
    env_file: ./tunnel.env
    restart: unless-stopped
    depends_on:
      - web
